name: Node.js CI/CD

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo su
            cd /home/ubuntu/BE-FINAL_PROJECT-TEAM_12

            git checkout development

            git config --global --add safe.directory /home/ubuntu/BE

            git pull origin development

            npm install
            
            pm2 describe app1 || pm2 start app.js --name app1

            pm2 restart app1 --update-env
